project_id = "nvxwjoalwlkhqnfgwdfq"

[functions.ai-chat]
verify_jwt = true

[functions.chat-history]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false